#!/bin/sh
#
#  archiveGraphs
###########################################################################
#
#  Purpose:  This script will archive 1 or more types of GO graphs.
#            The archive file(s) will be created in the GO graph directory.
#
#  Usage:
#
#      archiveGraphs  { -d -m -o }
#
#          where
#              -d is an option that tells the script to archive the
#                  ortho disease GO graphs
#              -m is an option that tells the script to archive the
#                  marker GO graphs
#              -o is an option that tells the script to archive the
#                  orthology GO graphs
#
#  Env Vars:
#
#      See the configuration file.
#
#  Inputs:
#
#      - 1 or more sets of GO graphs
#
#  Outputs:
#
#      - Archive files for 1 or more sets of GO graphs
#
#  Exit Codes:
#
#      0:  Successful completion
#      1:  Fatal error occurred
#
#  Assumes:  None
#
#  Implementation:
#
#  Notes:  None
#
###########################################################################

cd `dirname $0`

. ./Configuration

showUsage ()
{
echo "Usage: $0 { -d -m -o }"
}

DO_ORTHODISEASE=No
DO_MARKER=No
DO_ORTHOLOGY=No

#
# Check the arguments to the script to determine what type of GO graphs
# need to be archived.
#
ARGS=`getopt dmo $*`
if [ $? != 0 ]
then
    showUsage
    exit 1
fi
set -- ${ARGS}
for i
do
    case $i in
        -d) DO_ORTHODISEASE=Yes; shift;;
        -m) DO_MARKER=Yes; shift;;
        -o) DO_ORTHOLOGY=Yes; shift;;
        --) shift; break;;
    esac
done

#
# Exit the script if no options were used.
#
if [ "${DO_ORTHODISEASE}" = "No" -a "${DO_MARKER}" = "No" -a "${DO_ORTHOLOGY}" = "No" ]
then
    showUsage
    exit 1
fi

#
# Function to archive a specific set of GO graphs.
#
doArchive ()
{
    ARCHIVE_FILE=$1  # Name of the archive file to be created.
    SOURCE_DIR=$2    # Full path of the directory to be archived.

    #
    # Make sure the source directory exists.
    #
    if [ ! -d ${SOURCE_DIR} ]
    then
        echo "Directory does not exists: ${SOURCE_DIR}"
        exit 1
    fi

    #
    # Create the archive.
    #
    echo "Archive file: ${ARCHIVE_FILE}"
    cd ${SOURCE_DIR}
    tar -czf ${ARCHIVE_FILE} . 
}

#
# Archive the ortho disease GO graphs.
#
if [ "${DO_ORTHODISEASE}" = "Yes" ]
then
    echo "Create ortho disease GO graph archive"
    doArchive ${ORTHODISEASE_ARCHIVE} ${ORTHODISEASE_SRC_DIR}
fi

#
# Archive the marker GO graphs.
#
if [ "${DO_MARKER}" = "Yes" ]
then
    echo "Create marker GO graph archive"
    doArchive ${MARKER_ARCHIVE} ${MARKER_SRC_DIR}
fi

#
# Archive the orthology GO graphs.
#
if [ "${DO_ORTHOLOGY}" = "Yes" ]
then
    echo "Create orthology GO graph archive"
    doArchive ${ORTHOLOGY_ARCHIVE} ${ORTHOLOGY_SRC_DIR}
fi

exit 0
