#!/bin/sh
#
#  copyGraphs
###########################################################################
#
#  Purpose:  This script will copy 1 or more types of GO graphs into
#            new directories under the GO graphs directory.
#
#  Usage:
#
#      copyGraphs  { -d new_orthodisease_directory
#                    -m new_marker_directory
#                    -o new_orthology_directory }
#
#          where
#              -d is an option used to specify a new directory name to copy
#                  ortho disease GO graphs into
#              -m is an option used to specify a new directory name to copy
#                  marker GO graphs into
#              -o is an option used to specify a new directory name to copy
#                  orthology GO graphs into
#
#  Env Vars:
#
#      See the configuration file.
#
#  Inputs:
#
#      - 1 or more sets of GO graphs
#
#  Outputs:
#
#      - 1 or more new GO graph directories
#
#  Exit Codes:
#
#      0:  Successful completion
#      1:  Fatal error occurred
#
#  Assumes:  None
#
#  Implementation:
#
#  Notes:  None
#
###########################################################################

cd `dirname $0`

. ./Configuration

showUsage ()
{
echo "Usage: $0 { -d new_orthodisease_directory"
echo "           -m new_marker_directory"
echo "           -o new_orthology_directory }"
}

ORTHODISEASE_DIR=""
MARKER_DIR=""
ORTHOLOGY_DIR=""

#
# Check the arguments to the script to determine what type of GO graphs
# need to be copied.
#
ARGS=`getopt d:m:o: $*`
if [ $? != 0 ]
then
    showUsage
    exit 1
fi
set -- ${ARGS}
for i
do
    case $i in
        -d) shift; ORTHODISEASE_DIR=$1; shift;;
        -m) shift; MARKER_DIR=$1; shift;;
        -o) shift; ORTHOLOGY_DIR=$1; shift;;
        --) shift; break;;
    esac
done

#
# Exit the script if no options were used. 
#
if [ "${ORTHODISEASE_DIR}" = "" -a "${MARKER_DIR}" = "" -a "${ORTHOLOGY_DIR}" = "" ]
then
    showUsage
    exit 1
fi

#
# Function to copy a specific set of GO graphs to a new directory.
#
doCopy ()
{
    NEW_DIR=$1     # Name of the new directory to be created.
    SOURCE_DIR=$2  # Full path of the directory to be copied.

    #
    # Make sure the new directory does not already exist.
    #
    cd ${GOGRAPHS_DIR}
    if [ -d ${NEW_DIR} ]
    then
        echo "Directory already exists: ${NEW_DIR}"
        exit 1
    fi

    #
    # Make sure the source directory exists.
    #
    if [ ! -d ${SOURCE_DIR} ]
    then
        echo "Directory does not exists: ${SOURCE_DIR}"
        exit 1
    fi

    #
    # Copy the GO graphs to the new directory.
    #
    echo "Copy GO graphs to: ${GOGRAPHS_DIR}/${NEW_DIR}"
    cp -R ${SOURCE_DIR} ${NEW_DIR}
}

#
# Set up new ortho disease GO graphs.
#
if [ "${ORTHODISEASE_DIR}" != "" ]
then
    echo "Set up ortho disease GO graphs"
    doCopy ${ORTHODISEASE_DIR} ${ORTHODISEASE_SRC_DIR}
fi

#
# Set up new marker GO graphs.
#
if [ "${MARKER_DIR}" != "" ]
then
    echo "Set up marker GO graphs"
    doCopy ${MARKER_DIR} ${MARKER_SRC_DIR}
fi

#
# Set up new orthology GO graphs.
#
if [ "${ORTHOLOGY_DIR}" != "" ]
then
    echo "Set up orthology GO graphs"
    doCopy ${ORTHOLOGY_DIR} ${ORTHOLOGY_SRC_DIR}
fi

exit 0
