#!/bin/sh
#
#  extractGraphs
###########################################################################
#
#  Purpose:  This script will extract 1 or more types of GO graphs from
#            archive file(s) into new directories. Each new directory is
#            created under the GO graph directory.
#
#  Usage:
#
#      extractGraphs  { -d new_orthodisease_directory
#                       -m new_marker_directory
#                       -o new_orthology_directory }
#
#          where
#              -d is an option used to specify a new directory name to copy
#                  ortho disease GO graphs into
#              -m is an option used to specify a new directory name to copy
#                  marker GO graphs into
#              -o is an option used to specify a new directory name to copy
#                  orthology GO graphs into
#
#  Env Vars:
#
#      See the configuration file.
#
#  Inputs:
#
#      - 1 or more archive files
#
#  Outputs:
#
#      - 1 or more new GO graph directories
#
#  Exit Codes:
#
#      0:  Successful completion
#      1:  Fatal error occurred
#
#  Assumes:
#
#      1) The ortho disease GO graphs archive exists in the GO graph directory
#         when the "-d" option is used.
#      2) The marker GO graphs archive exists in the GO graph directory
#         when the "-m" option is used.
#      3) The orthology GO graphs archive exists in the GO graph directory
#         when the "-o" option is used.
#
#  Implementation:
#
#  Notes:  None
#
###########################################################################

cd `dirname $0`

. ./Configuration

showUsage ()
{
echo "Usage: $0 { -d new_orthodisease_directory"
echo "           -m new_marker_directory"
echo "           -o new_orthology_directory }"
}

ORTHODISEASE_DIR=""
MARKER_DIR=""
ORTHOLOGY_DIR=""

#
# Check the arguments to the script to determine what type of GO graphs
# need to be extracted.
#
ARGS=`getopt d:m:o: $*`
if [ $? != 0 ]
then
    showUsage
    exit 1
fi
set -- ${ARGS}
for i
do
    case $i in
        -d) shift; ORTHODISEASE_DIR=$1; shift;;
        -m) shift; MARKER_DIR=$1; shift;;
        -o) shift; ORTHOLOGY_DIR=$1; shift;;
        --) shift; break;;
    esac
done

#
# Exit the script if no options were used.
#
if [ "${ORTHODISEASE_DIR}" = "" -a "${MARKER_DIR}" = "" -a "${ORTHOLOGY_DIR}" = "" ]
then
    showUsage
    exit 1
fi

#
# Function to extract GO graphs from an archive file to a new directory.
#
doExtract ()
{
    ARCHIVE_FILE=$1  # Name of the archive file to be created.
    NEW_DIR=$2       # Name of the new directory to be created.

    #
    # Make sure the archive file exists.
    #
    if [ ! -r ${ARCHIVE_FILE} ]
    then
        echo "Missing archive file: ${ARCHIVE_FILE}"
        exit 1
    fi
    echo "Archive file: ${ARCHIVE_FILE}"

    #
    # Make sure the new directory does not already exist and create it.
    #
    cd ${GOGRAPHS_DIR}
    if [ -d ${NEW_DIR} ]
    then
        echo "Directory already exists: ${NEW_DIR}"
        exit 1
    fi
    mkdir ${NEW_DIR}

    #
    # Extract the GO graph archive into the new directory.
    #
    cd ${NEW_DIR}
    echo "Extract GO graphs to: ${GOGRAPHS_DIR}/${NEW_DIR}"
    tar -xzf ${ARCHIVE_FILE}
}

#
# Set up new ortho disease GO graphs.
#
if [ "${ORTHODISEASE_DIR}" != "" ]
then
    echo "Extract ortho disease GO graphs"
    doExtract ${ORTHODISEASE_ARCHIVE} ${ORTHODISEASE_DIR}
fi

#
# Set up new marker GO graphs.
#
if [ "${MARKER_DIR}" != "" ]
then
    echo "Extract marker GO graphs"
    doExtract ${MARKER_ARCHIVE} ${MARKER_DIR}
fi

#
# Set up new orthology GO graphs.
#
if [ "${ORTHOLOGY_DIR}" != "" ]
then
    echo "Extract orthology GO graphs"
    doExtract ${ORTHOLOGY_ARCHIVE} ${ORTHOLOGY_DIR}
fi

exit 0
