#!/bin/sh
#
#  extractGraphs
###########################################################################
#
#  Purpose:  This script will extract the marker and/or orthology GO graphs
#            from the archive file(s) into new directories. Each new
#            directory is created under the GO graph directory.
#
#  Usage:
#
#         extractGraphs { -m new_marker_directory -o new_orthology_directory }
#
#          where
#              -m is an option used to specify a new directory name to copy
#                  marker GO graphs into
#              -o is an option used to specify a new directory name to copy
#                  orthology GO graphs into
#
#  Env Vars:
#
#      See the configuration file.
#
#  Inputs:
#
#      - Marker and/or orthology archive files
#
#  Outputs:
#
#      - New marker and/or orthology GO graph directories
#
#  Exit Codes:
#
#      0:  Successful completion
#      1:  Fatal error occurred
#
#  Assumes:
#
#      1) The marker GO graphs archive exists in the GO graph directory
#         when the "-m" option is used.
#      2) The orthology GO graphs archive exists in the GO graph directory
#         when the "-o" option is used.
#
#  Implementation:
#
#  Notes:  None
#
###########################################################################

cd `dirname $0`

. ./Configuration

USAGE="Usage: $0 { -m new_marker_directory -o new_orthology_directory }"

MARKER_ARCHIVE=${GOGRAPHS_DIR}/marker.cpio
ORTHOLOGY_ARCHIVE=${GOGRAPHS_DIR}/orthology.cpio

MARKER_DIR=""
ORTHOLOGY_DIR=""

#
# Check the arguments to the script to determine what type of GO graphs
# need to be extracted.
#
ARGS=`getopt m:o: $*`
if [ $? != 0 ]
then
    echo ${USAGE}
    exit 1
fi
set -- ${ARGS}
for i
do
    case $i in
        -m) shift; MARKER_DIR=$1; shift;;
        -o) shift; ORTHOLOGY_DIR=$1; shift;;
        --) shift; break;;
    esac
done

#
# Exit the script if neither marker nor orthology options were used.
#
if [ "${MARKER_DIR}" = "" -a "${ORTHOLOGY_DIR}" = "" ]
then
    echo ${USAGE}
    exit 1
fi

#
# Set up new marker GO graphs.
#
if [ "${MARKER_DIR}" != "" ]
then
    #
    # Make sure the marker GO graph archive exists.
    #
    if [ ! -r ${MARKER_ARCHIVE} ]
    then
        echo "Missing marker graph archive: ${MARKER_ARCHIVE}"
        exit 1
    fi
    echo "Marker GO graph archive: ${MARKER_ARCHIVE}"

    #
    # Make sure the new marker directory does not already exist and
    # create it.
    #
    cd ${GOGRAPHS_DIR}
    if [ -d ${MARKER_DIR} ]
    then
        echo "Directory already exists: ${MARKER_DIR}"
        exit 1
    fi
    mkdir ${MARKER_DIR}

    #
    # Extract the marker GO graph archive into the new directory.
    #
    cd ${MARKER_DIR}
    echo "Extract marker GO graphs to: ${GOGRAPHS_DIR}/${MARKER_DIR}"
    cpio -idmu < ${MARKER_ARCHIVE}
fi

#
# Set up new orthology GO graphs.
#
if [ "${ORTHOLOGY_DIR}" != "" ]
then
    #
    # Make sure the orthology GO graph archive exists.
    #
    if [ ! -r ${ORTHOLOGY_ARCHIVE} ]
    then
        echo "Missing orthology graph archive: ${ORTHOLOGY_ARCHIVE}"
        exit 1
    fi
    echo "Orthology GO graph archive: ${ORTHOLOGY_ARCHIVE}"

    #
    # Make sure the new orthology directory does not already exist and
    # create it.
    #
    cd ${GOGRAPHS_DIR}
    if [ -d ${ORTHOLOGY_DIR} ]
    then
        echo "Directory already exists: ${ORTHOLOGY_DIR}"
        exit 1
    fi
    mkdir ${ORTHOLOGY_DIR}

    #
    # Extract the orthology GO graph archive into the new directory.
    #
    cd ${ORTHOLOGY_DIR}
    echo "Extract orthology GO graphs to: ${GOGRAPHS_DIR}/${ORTHOLOGY_DIR}"
    cpio -idmu < ${ORTHOLOGY_ARCHIVE}
fi

exit 0
