#!/bin/sh
#
#  installGraphs
###########################################################################
#
#  Purpose:  This script will copy 1 or more types of GO graphs into new
#            directories, change the symbolic link(s) and update the WI.
#
#  Usage:
#
#      installGraphs  { -d new_orthodisease_directory
#                       -m new_marker_directory
#                       -o new_orthology_directory }
#
#          where
#              -d is an option used to specify a new directory name to copy
#                  ortho disease GO graphs into
#              -m is an option used to specify a new directory name to copy
#                  marker GO graphs into
#              -o is an option used to specify a new directory name to copy
#                  orthology GO graphs into
#
#  Env Vars:
#
#      See the configuration file.
#
#  Inputs:
#
#      - 1 or more sets of GO graphs
#
#  Outputs:
#
#      - 1 or more new GO graph directories
#
#  Exit Codes:
#
#      0:  Successful completion
#      1:  Fatal error occurred
#
#  Assumes:  None
#
#  Implementation:
#
#  Notes:  None
#
###########################################################################

cd `dirname $0`

. ./Configuration

showUsage ()
{
echo "Usage: $0 { -d new_orthodisease_directory"
echo "           -m new_marker_directory"
echo "           -o new_orthology_directory }"
}

COPY_SCRIPT=`pwd`/copyGraphs

ORTHODISEASE_DIR=""
MARKER_DIR=""
ORTHOLOGY_DIR=""

#
# Check the arguments to the script to determine what type of GO graphs
# need to be copied.
#
ARGS=`getopt d:m:o: $*`
if [ $? != 0 ]
then
    showUsage
    exit 1
fi
set -- ${ARGS}
for i
do
    case $i in
        -d) shift; ORTHODISEASE_DIR=$1; shift;;
        -m) shift; MARKER_DIR=$1; shift;;
        -o) shift; ORTHOLOGY_DIR=$1; shift;;
        --) shift; break;;
    esac
done

#
# Exit the script if no options were used. 
#
if [ "${ORTHODISEASE_DIR}" = "" -a "${MARKER_DIR}" = "" -a "${ORTHOLOGY_DIR}" = "" ]
then
    showUsage
    exit 1
fi

#
# Function to install a specific set of GO graphs.
#
doInstall ()
{
    OPTION=$1    # Option that determines the type of GO graphs.
    NEW_DIR=$2   # Name of the new directory to be created.
    SYM_LINK=$3  # Name of the symbolic link to point to the new directory.

    #
    # Copy the GO graphs to the new directory.
    #
    ${COPY_SCRIPT} ${OPTION} ${NEW_DIR}
    if [ $? -ne 0 ]
    then
        exit 1
    fi

    #
    # Swap the symbolic link to the new directory.
    #
    echo "Create symbolic link: ${SYM_LINK} -> ${NEW_DIR}"
    cd ${GOGRAPHS_DIR}
    rm -f ${SYM_LINK}
    ln -s ${NEW_DIR} ${SYM_LINK}
}

#
# Set up new ortho disease GO graphs.
#
if [ "${ORTHODISEASE_DIR}" != "" ]
then
    doInstall -d ${ORTHODISEASE_DIR} ${ORTHODISEASE_LINK}
fi

#
# Set up new marker GO graphs.
#
if [ "${MARKER_DIR}" != "" ]
then
    doInstall -m ${MARKER_DIR} ${MARKER_LINK}
fi

#
# Set up new orthology GO graphs.
#
if [ "${ORTHOLOGY_DIR}" != "" ]
then
    doInstall -o ${ORTHOLOGY_DIR} ${ORTHOLOGY_LINK}
fi

#
# Update the WI.
#
if [ -d ${MGI_LIVE}/wi ]
then
    cd ${MGI_LIVE}/wi/admin
    echo "Run download_goGraphs on the WI"
    download_goGraphs
fi

exit 0
